# Site settings
title: DTO Design Guide
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

markdown: kramdown

exclude: [node_modules, _data]

gems:
  - jekyll-assets

assets:
  sources:
    - _assets/scss
    - node_modules

page_gen:
  - data: 'styleguide-sections'
    template: 'section'
    name: 'header'
    dir: 'sections'
