# Site settings
title: DTO Design Guide
description: A living style guide of the UI-Kit CSS framework.
github_url: https://github.com/AusDTO/gov-au-ui-kit
#google_analytics: UA-72255206-3
uikit_base_url: https://gov-au-ui-kit.apps.staging.digital.gov.au/latest/

# Build settings
markdown: kramdown
exclude: [node_modules, _data, vendor]
gems:
  - jekyll-assets
assets:
  sources:
    - _assets/scss
    - _assets/vendor

# Plugin settings
page_gen:
  - data: "data-sections"
    template: "section"
    name: "header"
    dir: "sections"
